const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";


const RESET_PRODUCT = "RESET_PRODUCT";

const INCREASE_QUANTITY = "INCREASE_QUANTITY";
const DECREASE_QUANTITY = "DECREASE_QUANTITY";


export { PRODUCT_FETCH_SUCCESS, PRODUCT_FETCH_FAILURE,RESET_PRODUCT, INCREASE_QUANTITY, DECREASE_QUANTITY };
